# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"run_tests": "00_tools.ipynb"}

modules = ["tools.py"]

doc_url = "https://atomscott.github.io/atcoder_nb/"

git_url = "https://github.com/atomscott/atcoder_nb/tree/master/"

def custom_doc_links(name): return None
