# AUTOGENERATED! DO NOT EDIT! File to edit: 00_tools.ipynb (unless otherwise specified).

__all__ = ['run_tests']

# Cell
import os
from glob import glob

from atcodertools.tools.tester import run_all_tests
from atcodertools.common.judgetype import ErrorType, NormalJudge, DecimalJudge, Judge, JudgeType

# Cell
def run_tests(alphabet):
    inputs = sorted(glob(f"{alphabet}/in*.txt"))
    outputs = sorted(glob(f"{alphabet}/out*.txt"))

    return run_all_tests(f'{alphabet}/main.py', inputs, outputs, 1, False, False, NormalJudge())